[[redirects]]
  from   = "/mapsforall"
  to     = "https://mapsforall.netlify.app/"
  status = 200
  force  = true

[[redirects]]
  from   = "/mapsforall/*"
  to     = "https://mapsforall.netlify.app/:splat"
  status = 200
  force  = true
