[build]
  # Ajuste o comando de build e a pasta de publicação conforme seu setup
  command = "npm run build"
  publish = ".next"  # se usar @netlify/plugin-nextjs
  # ou publish = "out"   # se você exporta como estático

[[redirects]]
  # Proxy transparente de /mapsforall → mapsforall.netlify.app, preservando o basePath
  from   = "/mapsforall/*"
  to     = "https://mapsforall.netlify.app/mapsforall/:splat"
  status = 200
  force  = true
  